eureka:
  client:
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:8040}}

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
---
spring:
  profiles: url

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    review-service:
      path: /review-service/**
      serviceId: REVIEW #http://localhost:9010/api/reviews-service/reviews?eventId=1
    review-by-url:
      path: /review-url/**
      url: http://localhost:9010 #http://localhost:9010/api/reviews-url/reviews?eventId=1

---
spring:
  profiles: service

zuul:
  ignoredServices: "*"
  prefix: /api/v1
  routes:
    event: /events/** #http://localhost:8040/api/events/events
    review: /reviews/**
    event-composite: /composite/**
---

spring:
  profiles: docker

zuul:
  ignoredServices: "*"
  prefix: /api/v1
  routes:
    event: /events/**
    review: /reviews/**
    event-composite: /composite/**
    recommendation: /recommendations/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/