eureka:
  client:
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:8030}}
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: event-composite

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/